-- 성종환 -------------------------------------------------------------------------

-- 1-1. MEMBER 테이블 추가
CREATE TABLE "MEMBER" (
	"MEMBER_NO"					NUMBER 					NOT NULL,
	"MEMBER_EMAIL"			NVARCHAR2(50)		NOT NULL,
	"MEMBER_PW"					NVARCHAR2(50)		NOT NULL,
	"MEMBER_NICKNAME"		NVARCHAR2(10)		NOT NULL,
	"PROFILE_IMG"				VARCHAR2(300)		NULL,
	"ENROLL_DATE"				DATE						DEFAULT SYSDATE NOT NULL,
	"MEMBER_DEL_FL"			CHAR(1)					DEFAULT 'N' NOT NULL, 
	"MEMBER_BIRTH_DATE"	VARCHAR(8)			NOT NULL,
	"MEMBER_TEL"				VARCHAR(13)			NOT NULL,
	"MEMBER_ADDRESS"		NVARCHAR2(300)	NULL,
	"AUTHORITY"					NUMBER					DEFAULT 1 NOT NULL,
	"MEMBER_BG"					VARCHAR2(20)		NOT NULL
);

	/* 
	 수정 사항
	 1) MEMBER_ADDRESS : 기본값 NULL 로 변경 
	    - 사유 : 회원가입 시 필수입력 X
	 
	 2) MEMBER_BG : NUMBER 타입으로 변경
	    - 사유 : 현 단계에서 마이페이지 제공 컬러테마 총 8개
	  					 따라서 NUMBER 형으로 지정하여 1~8까지 각각 상응하는 컬러테마 지정하는 게 가능 및
	  					 추후 컬러 추가하기에도 용이하며 NVARCHAR로 할 시 오타 발생 상황 방지 용이 */
	 
ALTER TABLE "MEMBER" MODIFY ("MEMBER_ADDRESS" NULL);

COMMIT;

-- 1-2. 각 컬럼별 COMMENT 추가
COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원번호(PK)';
COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원 이메일';
COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME" IS '회원 별명(활동명)';
COMMENT ON COLUMN "MEMBER"."PROFILE_IMG" IS '회원 프로필 이미지';
COMMENT ON COLUMN "MEMBER"."MEMBER_DEL_FL" IS '탈퇴여부';
COMMENT ON COLUMN "MEMBER"."MEMBER_BIRTH_DATE" IS '생년월일';
COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '전화번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_ADDRESS" IS '주소';
COMMENT ON COLUMN "MEMBER"."AUTHORITY" IS '권한(1=회원 2=관리자)';
COMMENT ON COLUMN "MEMBER"."MEMBER_BG" IS '회원 테마색';


-- 2. MEMBER_NO 컬럼 PK 제약조건 추가
ALTER TABLE "MEMBER" 
ADD CONSTRAINT "PK_MEMBER" 
PRIMARY KEY ("MEMBER_NO");

-- 3-1. MEMBER_NO 에 들어갈 SEQUENCE 생성
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;

-- 3-2. 최초 번호 생성
SELECT SEQ_MEMBER_NO.NEXTVAL FROM DUAL; 

-- 3-3. 현재 번호 확인
SELECT SEQ_MEMBER_NO.CURRVAL FROM DUAL; 

-- 3-4. 증감 변경 
ALTER SEQUENCE SEQ_MEMBER_NO INCREMENT BY 1;

SELECT * FROM "MEMBER";

-- 성종환 ---------------------------------------------------------------------------------

CREATE TABLE "TIMETABLE" (
	"TIMETABLE_ID"	NUMBER	NOT NULL,	
	"DAY_OF_WEEK"		NUMBER	NOT NULL,
	"SEMESTER"			NVARCHAR2(10) NOT NULL,
	"SUBJECT"				NVARCHAR2(10)	NULL,
	"MEMBER_NO"			NUMBER	NOT NULL
);

/* 수정사항
 1) END_DATE 및 START_DATE 삭제
  - 사유 : 굳이 필요하지 않은 데이터인 듯하여 삭제하였습니다.
 
 2) SEMESTER(학기) 추가
  - 사유 : 1)과 관련하여, '2025년도 1학기', '2026년도 2학기' 등처럼 학기만 나타내주는 컬럼이 필요하여 추가
 
 3) DAY_OF_WEEK 을 NUMBER 타입으로 변경
  - 사유 : 일주일 단위기간을 숫자로 나타내어 오타로 인한 오류 방지 용이
  
 4) SUBJECT 를 NULL 허용으로 변경
  - 사유 : 반드시 7교시가 아니라 4교시, 5교시 등도 있을 수 있기 때문에 NULL 허용
*/

COMMENT ON COLUMN "TIMETABLE"."TIMETABLE_ID" IS '시간표번호(PK)';
COMMENT ON COLUMN "TIMETABLE"."DAY_OF_WEEK" IS '요일';
COMMENT ON COLUMN "TIMETABLE"."SEMESTER" IS '학기';
COMMENT ON COLUMN "TIMETABLE"."SUBJECT" IS '과목';
COMMENT ON COLUMN "TIMETABLE"."MEMBER_NO" IS '회원번호(FK)';

ALTER TABLE "TIMETABLE"
ADD CONSTRAINT "PK_TIMETABLE" 
PRIMARY KEY ("TIMETABLE_ID");

SELECT * FROM "TIMETABLE";

COMMIT;
---------------------------------------------------------------------------------------------------

-- !!!!!! 아래부터 주석처리함.
-- !!!!!! 필요한 거 잘라내서 추가해주세요

/* 

CREATE TABLE `BOARD_LIKE` (
	`MEMBER_NO`	NUMBER	NOT NULL	COMMENT '회원번호(PFK)',
	`BOARD_ID`	NUMBER	NOT NULL	COMMENT '게시글번호(PK)'
);

CREATE TABLE `TODO` (
	`TODO_NO`	NUMBER	NOT NULL	COMMENT '할일 번호(PK)',
	`TODO_TITLE`	VARCHAR(200)	NOT NULL	COMMENT '할일 제목',
	`TODO_CONTENT`	VARCHAR2(4000)	NOT NULL	COMMENT '할일 내용',
	`TODO_CHECK`	CHAR(1)	NULL	DEFAULT N	COMMENT '할일 체크',
	`TODO_DATE`	DATE	NOT NULL	COMMENT '할일 날짜',
	`MEMBER_NO`	NUMBER	NOT NULL	COMMENT '회원번호(FK)'
);

CREATE TABLE `COMMENT` (
	`COMMENT_NO`	NUMBER	NOT NULL	COMMENT '댓글 번호(PK)',
	`COMMENT_CONTENT`	VARCHAR2(4000)	NOT NULL	COMMENT '댓글 내용',
	`COMMENT_WRITE_DATE`	DATE	NOT NULL	COMMENT '댓글 작성일',
	`COMMENT_DEL_FL`	CHAR(1)	NOT NULL	DEFAULT DEFAULT	COMMENT '댓글 삭제 여부(Y/N)',
	`BOARD_NO`	NUMBER	NOT NULL	COMMENT '게시글 번호(PK)',
	`MEMBER_NO`	NUMBER	NOT NULL	COMMENT '회원번호(FK)',
	`PARENT_COMMENT_NO`	NUMBER	NOT NULL	COMMENT '부모 댓글 번호'
);

CREATE TABLE `DIARY` (
	`DIARY_NO`	NUMBER	NOT NULL	COMMENT '일기장 번호(PK)',
	`DIARY_DATE`	DATE	NOT NULL	COMMENT '일기장 날짜',
	`DIARY_TITLE`	NVARCHAR2(50)	NOT NULL	COMMENT '일기장 제목',
	`DIARY_CONTENT`	NVARCHAR2(2000)	NOT NULL	COMMENT '일기장 내용',
	`MEMBER_NO`	NUMBER	NOT NULL	COMMENT '회원번호(FK)'
);

CREATE TABLE `WRONG_NOTE` (
	`WRONG_NOTE_NO`	NUMBER	NOT NULL	COMMENT '할일 번호(PK)',
	`WRONG_NOTE_TITLE`	VARCHAR(200)	NOT NULL	COMMENT '오답노트 제목',
	`WRONG_NOTE_CONTENT`	VARCHAR2(4000)	NOT NULL	COMMENT '오답노트 내용',
	`WRONG_NOTE_DATE`	DATE	NOT NULL	DEFAULT SYSDATE	COMMENT '오답노트 작성일',
	`MEMBER_NO`	NUMBER	NOT NULL	COMMENT '회원번호(FK)'
);

CREATE TABLE `INQUIRY` (
	`INQUIRY_NO`	NUMBER	NOT NULL	COMMENT '문의 번호',
	`INQUIRY_TITLE`	NVARCHAR2(50)	NOT NULL	COMMENT '문의사항 분류',
	`INQUIRY_CONTENT`	NVARCHAR2(1000)	NOT NULL	COMMENT '세부문의사항',
	`INQUIRY_COMPLETE`	CHAR(1)	NOT NULL	DEFAULT N	COMMENT '조치완료여부(N/Y)',
	`INQUIRY_DATE`	DATE	NOT NULL	COMMENT '문의한 날짜',
	`INQUIRY_COMPLETE_DATE`	DATE	NOT NULL	COMMENT '답변한 날짜',
	`MEMBER_NO`	NUMBER	NOT NULL	COMMENT '회원번호(PK)'
);



CREATE TABLE `CHAT_MESSAGE` (
	`MSG_NO`	NUMBER	NOT NULL	COMMENT '메시지 고유 번호(PK)',
	`MESSAGE`	VARCHAR2(4000)	NOT NULL	COMMENT '메시지 내용',
	`READ_YN`	CHAR(1)	NOT NULL	COMMENT '읽음 여부("Y" 또는 "N")',
	`SEND_DATE`	DATE	NOT NULL	DEFAULT SYSDATE	COMMENT '보낸 시간(기본값: 현재시간)',
	`ROOM_NO2`	NUMBER	NOT NULL	COMMENT '채팅방 번호(PK)',
	`SENDER_NO`	NUMBER	NOT NULL	COMMENT '메시지보낸회원번호(PK)'
);

CREATE TABLE `UPLOAD_FILE` (
	`UPLOADFILE_NO`	NUMBER	NOT NULL	COMMENT '파일 번호',
	`UPLOADFILE_ORIGIN`	VARCHAR2(150)	NOT NULL	COMMENT '원본 파일명',
	`UPLOADFILE_PATH`	VARCHAR2(1000)	NOT NULL	COMMENT '파일 경로',
	`UPLOADFILE_STRG`	VARCHAR2(150)	NOT NULL	COMMENT '저장 파일명',
	`UPLOADFILE_SIZE`	NUMBER	NOT NULL	COMMENT '파일 크기',
	`UPLOADFILE_DATE`	DATE	NOT NULL	DEFAULT SYSDATE,
	`BOARD_ID`	NUMBER	NOT NULL	COMMENT '게시글번호(FK)'
);

CREATE TABLE `BOARD` (
	`BOARD_ID`	NUMBER	NOT NULL	COMMENT '게시글번호(PK)',
	`BOARD_TITLE`	NVARCHAR(20)	NOT NULL,
	`BIOARD_CONTENT`	TEXT	NOT NULL,
	`BOARD_VIEW_COUNT`	NUMBER	NOT NULL	DEFAULT 0,
	`BOARD_IS_DELETED`	CHAR(1)	NOT NULL	DEFAULT N	COMMENT 'N/Y',
	`BOARD_CREATE`	DATE	NOT NULL	DEFAULT SYSDATE,
	`BOARD_UPDATED`	DATE	NULL,
	`BOARD_TYPE_NO`	NUMBER	NOT NULL	COMMENT '게시판 종류코드반 번호(FK)',
	`MEMBER_NO2`	NUMBER	NOT NULL	COMMENT '회원번호(FK)'
);

CREATE TABLE `BOARD_IMG` (
	`IMG_NO`	NUMBER	NOT NULL	COMMENT '이미지 번호(PK)',
	`IMG_PATH`	VARCHAR(200)	NOT NULL	COMMENT '이미지 요청 경로',
	`IMG_ORIGINAL_NAME`	NVARCHAR2(50)	NOT NULL	COMMENT '이미지 원본명',
	`IMG_RENAME`	NVARCHAR2(50)	NOT NULL	COMMENT '이미지 변경명',
	`IMG_ORDER`	NUMBER	NULL	COMMENT '이미지 순서',
	`BOARD_NO`	NUMBER	NOT NULL	COMMENT '게시긃 번호',
	`BOARD_ID`	NUMBER	NOT NULL	COMMENT '게시글번호(FK)'
);

CREATE TABLE `ATTENDANCE` (
	`ATTENDANCE_DATE`	DATE	NOT NULL	COMMENT '출석시간(PK)',
	`MEMBER_NO`	NUMBER	NOT NULL	COMMENT '회원번호(PFK)',
	`ATTENDANCE_NO`	NUMBER	NOT NULL	COMMENT '출석고유번호(UNIQUE)'
);

CREATE TABLE `AUTH_KEY_EMAIL` (
	`EMAIL_KEY_NO`	NUMBER	NOT NULL	COMMENT '이메일 인증 키 번호(PK)',
	`EMAIL`	NVARCHAR2(50)	NOT NULL	COMMENT '이메일 주소',
	`AUTH_KEY`	CHAR(6)	NOT NULL	COMMENT '이메일 인증 번호',
	`AUTH_CREATE_TIME`	DATE	NOT NULL	DEFAULT SYSDATE	COMMENT '이메일 인증번호 생성 시간'
);

CREATE TABLE `D_DAY` (
	`D_DAY_NO`	NUMBER	NOT NULL	COMMENT 'D_DAY PK',
	`D_DAY_TITLE`	NVARCHAR2(20)	NULL,
	`D_DAY_MENT`	NVARCHAR2(100)	NULL,
	`D_DAY`	DATE	NULL,
	`MEMBER_NO`	NUMBER	NOT NULL	COMMENT '회원번호(FK)'
);

CREATE TABLE `POINT_LOG` (
	`POINT_LOG_ID`	NUMBER	NOT NULL	COMMENT '포인트번호(PK)',
	`POINT`	NUMBER	NOT NULL,
	`POINT_REASON`	NVARCHAR(255)	NOT NULL,
	`POINT_CREATE_AT`	DATE	NOT NULL,
	`MEMBER_NO`	NUMBER	NOT NULL	COMMENT '회원번호(PK)',
	`ATTENDANCE_NO`	NUMBER	NOT NULL	COMMENT '출석고유번호(UNIQUE)'
);

CREATE TABLE `BOARD_TYPE` (
	`BOARD_TYPE_NO`	NUMBER	NOT NULL	COMMENT '게시판 종류코드반 번호(PK)',
	`BOARD_TYPE_NAME`	VARCHAR(20)	NOT NULL	COMMENT '게시판 이름'
);

CREATE TABLE `CHAT_ROOM` (
	`ROOM_NO`	NUMBER	NOT NULL	COMMENT '채팅방 번호(PK)',
	`CREATE_DATE`	DATE	NOT NULL	DEFAULT SYSDATE	COMMENT '생성일',
	`PARTICIPANT`	NUMBER	NOT NULL	COMMENT '참여자(FK)',
	`OPEN_MEMBER`	NUMBER	NOT NULL	COMMENT '개설자(FK)'
);



ALTER TABLE `BOARD_LIKE` ADD CONSTRAINT `PK_BOARD_LIKE` PRIMARY KEY (
	`MEMBER_NO`,
	`BOARD_ID`
);

ALTER TABLE `TODO` ADD CONSTRAINT `PK_TODO` PRIMARY KEY (
	`TODO_NO`
);

ALTER TABLE `COMMENT` ADD CONSTRAINT `PK_COMMENT` PRIMARY KEY (
	`COMMENT_NO`
);

ALTER TABLE `DIARY` ADD CONSTRAINT `PK_DIARY` PRIMARY KEY (
	`DIARY_NO`
);

ALTER TABLE `WRONG_NOTE` ADD CONSTRAINT `PK_WRONG_NOTE` PRIMARY KEY (
	`WRONG_NOTE_NO`
);

ALTER TABLE `INQUIRY` ADD CONSTRAINT `PK_INQUIRY` PRIMARY KEY (
	`INQUIRY_NO`
);

ALTER TABLE `TIMETABLE` ADD CONSTRAINT `PK_TIMETABLE` PRIMARY KEY (
	`TIMETABLE_ID`
);

ALTER TABLE `CHAT_MESSAGE` ADD CONSTRAINT `PK_CHAT_MESSAGE` PRIMARY KEY (
	`MSG_NO`
);

ALTER TABLE `UPLOAD_FILE` ADD CONSTRAINT `PK_UPLOAD_FILE` PRIMARY KEY (
	`UPLOADFILE_NO`
);

ALTER TABLE `BOARD` ADD CONSTRAINT `PK_BOARD` PRIMARY KEY (
	`BOARD_ID`
);

ALTER TABLE `BOARD_IMG` ADD CONSTRAINT `PK_BOARD_IMG` PRIMARY KEY (
	`IMG_NO`
);

ALTER TABLE `ATTENDANCE` ADD CONSTRAINT `PK_ATTENDANCE` PRIMARY KEY (
	`ATTENDANCE_DATE`,
	`MEMBER_NO`
);

ALTER TABLE `AUTH_KEY_EMAIL` ADD CONSTRAINT `PK_AUTH_KEY_EMAIL` PRIMARY KEY (
	`EMAIL_KEY_NO`
);

ALTER TABLE `D_DAY` ADD CONSTRAINT `PK_D_DAY` PRIMARY KEY (
	`D_DAY_NO`
);

ALTER TABLE `POINT_LOG` ADD CONSTRAINT `PK_POINT_LOG` PRIMARY KEY (
	`POINT_LOG_ID`
);

ALTER TABLE `BOARD_TYPE` ADD CONSTRAINT `PK_BOARD_TYPE` PRIMARY KEY (
	`BOARD_TYPE_NO`
);

ALTER TABLE `CHAT_ROOM` ADD CONSTRAINT `PK_CHAT_ROOM` PRIMARY KEY (
	`ROOM_NO`
);



ALTER TABLE `BOARD_LIKE` ADD CONSTRAINT `FK_MEMBER_TO_BOARD_LIKE_1` FOREIGN KEY (
	`MEMBER_NO`
)
REFERENCES `MEMBER` (
	`MEMBER_NO`
);

ALTER TABLE `BOARD_LIKE` ADD CONSTRAINT `FK_BOARD_TO_BOARD_LIKE_1` FOREIGN KEY (
	`BOARD_ID`
)
REFERENCES `BOARD` (
	`BOARD_ID`
);

ALTER TABLE `ATTENDANCE` ADD CONSTRAINT `FK_MEMBER_TO_ATTENDANCE_1` FOREIGN KEY (
	`MEMBER_NO`
)
REFERENCES `MEMBER` (
	`MEMBER_NO`
);

*/